spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/receipts
    username: receipts
    password: receipts
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog-master.yml
    contexts: default
